#!/usr/bin/python3

from connect_menu import ConnectMenu
from machine_info import MachineInfo


def showConnectMenu():
    theMenu = ConnectMenu()
    theMenu.show()
    pass


def testMachineInfo():
    machineInfo = MachineInfo("localhost", 9000)
    print(machineInfo)
    pass    


def main():
    showConnectMenu()
    pass


if __name__ == "__main__":
    main()
        
